config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  resources :users
  namespace :admin do
    root "admins#index", as: :root
    resources :costs, :rooms, :room_costs
    resources :users do
      get "get_user_cost_info", on: :collection
    end
    resources :statistic
  end
end

app/models/room_cost.rb
class RoomCost < ApplicationRecord
  belongs_to :cost, optional: true
  belongs_to :room

  ATTRIBUTE_PARAMS = [:amount_electric_consumption, :room_id, :month, :cost_id]

  validate :check_duplicate_month

  scope :get_by_month, -> month do
    where("MONTH(month) = ? and YEAR(month) = ?", month.month, month.year)
  end

  def check_duplicate_month
    if self.id
      exist_month = RoomCost.where("MONTH(month) = ? and YEAR(month) = ? and room_id = ? and id <> ?",
        self.month.month, self.month.year, self.room_id, self.id).first
    else
      exist_month = RoomCost.where("MONTH(month) = ? and YEAR(month) = ? and room_id = ?",
        self.month.month, self.month.year, self.room_id).first
    end
    if exist_month.nil?
      true
    else
      errors.add(:duplicate_month, "Tháng đã tồn tại")
    end
  end

  def get_current_consumption month
    last_month_amount_consumption = get_last_month_room_cost month
    current_consumption = 0
    if last_month_amount_consumption
      current_consumption = self.amount_electric_consumption - last_month_amount_consumption.amount_electric_consumption
    else
      current_consumption = self.amount_electric_consumption
    end
    current_consumption
  end

  def get_last_month_room_cost month
    last_month = month - 1.month
    RoomCost.where("MONTH(month) = ? and YEAR(month) = ? and room_id = ?", last_month.month, last_month.year, self.room_id).first
  end
end

app/controllers/admin/room_costs_controller.rb
class Admin::RoomCostsController < ApplicationController
  load_and_authorize_resource
  layout "admin"

  def index
    @room_costs = RoomCost.all.page params[:page]
  end

  def create
    cost_service = CostCaculateService.new
    if @room_cost.valid?
      electric_cost = cost_service.electric_cost @room_cost.get_current_consumption(@room_cost.month)
      @room_cost.update_attributes electric_cost: electric_cost
      @room_cost.save
      update_cost_id @room_cost
      cost_service.auto_create_user_cost @room_cost

      flash[:success] = t ".create_success"
      redirect_to admin_room_costs_url
    else
      flash[:danger] = t ".fail"
      render :new
    end
  end

  def edit
  end

  def show

  end

  def update
    cost_service = CostCaculateService.new
    if @room_cost.update_attributes room_cost_params
      electric_cost = cost_service.electric_cost @room_cost.get_current_consumption(@room_cost.month)
      @room_cost.update_attributes electric_cost: electric_cost
      update_cost_id @room_cost
      cost_service.auto_create_user_cost @room_cost

      flash[:success] = t ".update_success"

      redirect_to admin_room_costs_url
    else
      render :edit
    end
  end

  private
  def room_cost_params
    params.require(:room_cost).permit(RoomCost::ATTRIBUTE_PARAMS)
  end

  def update_cost_id room_cost
    cost = Cost.get_by_month room_cost.month
    if cost.present?
      room_cost.update cost_id: cost[0] ? cost[0].id : cost.id
    end
  end
end

app/views/admin/room_costs/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for [:admin, @room_cost], html: {multipart: true}  do |f| %>
      <%=  render "shared/error_messages", object: @room_cost %>

      <div class="form-group">
        <%= f.label :month, t(".month") %><br />
        <%= f.text_field :month, placeholder: 'Ngày/Tháng/Năm', value: @room_cost.month&.strftime("%d/%m/%Y"),
          class: "form-control datetime-picker", required: "true" %>
      </div>

      <div class="form-group">
        <%= f.label :amount_electric_consumption, t(".amount_electric_consumption") %><br />
        <%= f.text_field :amount_electric_consumption,
          class: "form-control", required: "true", type: :number %>
      </div>

      <div class="form-group">
        <%= f.collection_select :room_id, Room.all, :id, :name,{}, {class: "form-control"} %>
      </div>

      <div class="actions">
        <%= f.submit t(".save"), class: "btn btn-default" %>
      </div>
    <% end %>
    <br />
    <%= link_to "Quay lại", root_path %>
  </div>
</div>

app/views/admin/room_costs/edit.html.erb
<h2 class="text-center"><%= t ".edit_room" %></h2>
<%= render "form" %>

app/views/admin/room_costs/index.html.erb
<h2 class="text-center"><%= t ".room_costs" %></h2>
<div class="pull-left btn-add-cost">
  <%= link_to "  Tạo mới", new_admin_room_cost_path,
    class: "fa fa-plus btn btn-default" %>
</div>
<div id="table-floors">
  <table class="table table-hover new-order table-bordered">
    <thead>
      <tr class="info row">
        <th class="col-md-1"><%= t ".month" %></th>
        <th class="col-md-2"><%= t ".name_room" %></th>
        <th class="col-md-2"><%= t ".amount_electric_consumption" %></th>
        <th class="col-md-2"><%= t ".real_consumption" %></th>
        <th class="col-md-2"><%= t ".electric_cost" %></th>
        <th class="col-md-2"><%= t ".updated_time" %></th>
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
      <% @room_costs.each do |fcost| %>
        <tr class="row">
          <td class="col-md-1"><%= fcost.month ? fcost.month.strftime("%m/%Y") : fcost.month %></td>
          <td class="col-md-2"><%= fcost.room.name %></td>
          <th class="col-md-2"><%= fcost.amount_electric_consumption %></th>
          <th class="col-md-2"><%= fcost.get_current_consumption fcost.month %></th>
          <th class="col-md-2"><%= fcost.electric_cost ? number_to_currency(fcost.electric_cost.round, unit: "VND", delimiter: ".", separator: ",", precision: 0, format: "%n %u") : fcost.electric_cost.round %></th>
          <th class="col-md-2"><%= fcost.updated_at.strftime("%d/%m/%Y - %H:%M") %></th>
          <td class="col-md-1">
            <%= link_to edit_admin_room_cost_path(fcost),
              class: "btn btn-default button-1" do %>
              <i class="fa fa-wrench"><%= t ".edit_room_cost" %></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <%= paginate @room_costs %>
    </tbody>
  </table>
</div>

app/views/admin/room_costs/new.html.erb
<h2 class="text-center"><%= t ".create_room_cost" %></h2>
<%= render "form" %>