config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  resources :users
  namespace :admin do
    root "admins#index", as: :root
    resources :costs, :rooms, :room_costs
    resources :users do
      get "get_user_cost_info", on: :collection
    end
    resources :statistic
  end
end

app/models/cost.rb
class Cost < ApplicationRecord

  ATTRIBUTE_PARAMS = [:month, :total_payment_electric, :total_payment_water, :amount_electric,
    :amount_water]

  has_many :room_costs

  validate :check_duplicate_month

  scope :get_by_month, -> month do
    where("MONTH(month) = ? and YEAR(month) = ?", month.month, month.year).first
  end

  def devide_to_person
    cost_last_month = Cost.where("MONTH(month) = ? and YEAR(month) = ?", self.month.month - 1, self.month.year).first

  end

  def check_duplicate_month
    if self.id
      exist_month = Cost.where("MONTH(month) = ? and YEAR(month) = ? and id <> ?", self.month.month, self.month.year, self.id).first
    else
      exist_month = Cost.where("MONTH(month) = ? and YEAR(month) = ?", self.month.month, self.month.year).first
    end

    if exist_month.nil?
      true
    else
      errors.add(:duplicate_month, "Tháng đã tồn tại")
    end
  end

  class << self
    def statistic_electric
      payment_electric = Cost.where("month >= ? and month <= ?", Date.today.beginning_of_year, Date.today).map(&:total_payment_electric)
    end

    def statistic_water
      payment_water = Cost.where("month >= ? and month <= ?", Date.today.beginning_of_year, Date.today).map(&:total_payment_water)
    end

    def get_months
      months = Cost.where("month >= ? and month <= ?", Date.today.beginning_of_year, Date.today).pluck :month
      month_array = []
      months.each do |m|
        month_array << I18n.t(".month") + m.month.to_s
      end
      month_array
    end

    def get_current_cost
      Cost.where("MONTH(month) = ? and YEAR(month) = ?", Date.today.month, Date.today.year).first
    end
  end
end

app/controllers/admin/costs_controller.rb
class Admin::CostsController < ApplicationController
  load_and_authorize_resource
  layout "admin"

  def index
    @costs = Cost.all.page params[:page]
  end

  def create
    if @cost.valid?
      @cost.save
      update_room_cost @cost
      flash[:success] = t ".create_success"
      redirect_to admin_costs_url
    else
      flash[:danger] = t ".fail"
      render :new
    end
  end

  def edit
  end

  def show

  end

  def update
    if @cost.update_attributes cost_params
      update_room_cost @cost
      flash[:success] = t ".update_success"

      redirect_to admin_costs_url
    else
      render :edit
    end
  end

  private
  def cost_params
    params.require(:cost).permit(Cost::ATTRIBUTE_PARAMS)
  end

  def update_room_cost cost
    room_costs = RoomCost.get_by_month cost.month
    caculate_service = CostCaculateService.new
      if room_costs.present?
        room_costs.each do |rcost|
          rcost.update cost_id: cost.id
          caculate_service.auto_create_user_cost rcost
        end
      end
  end
end

app/views/admin/costs/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for [:admin, @cost], html: {multipart: true}  do |f| %>
      <%=  render "shared/error_messages", object: @cost %>
      <div class="form-group">
        <%= f.label :month, t(".month") %><br />
        <%= f.text_field :month, placeholder: 'Ngày/Tháng/Năm', value: @cost.month&.strftime("%d/%m/%Y"),
          class: "form-control datetime-picker", required: "true" %>
      </div>

      <div class="form-group">
        <%= f.label :total_payment_electric, t(".total_payment_electric") %><br />
        <%= f.text_field :total_payment_electric, autocomplete: false, class: "form-control",
          required: "true", type: :number %>
      </div>

      <div class="form-group">
        <%= f.label :total_payment_water, t(".total_payment_water") %><br />
        <%= f.text_field :total_payment_water, autocomplete: false, class: "form-control",
          required: "true", type: :number %>
      </div>

      <div class="form-group">
        <%= f.label :amount_electric, t(".amount_electric") %><br />
        <%= f.text_field :amount_electric, autocomplete: false, class: "form-control",
          required: "true", type: :number %>
      </div>

      <div class="form-group">
        <%= f.label :amount_water, t(".amount_water") %><br />
        <%= f.text_field :amount_water, autocomplete: false, class: "form-control",
          required: "true", type: :number %>
      </div>

      <div class="actions">
        <%= f.submit t(".save"), class: "btn btn-default" %>
      </div>
    <% end %>
    <br />
    <%= link_to "Quay lại", root_path %>
  </div>
</div>

app/views/admin/costs/edit.html.erb
<h2 class="text-center"><%= t ".edit_cost" %></h2>
<%= render "form" %>

app/views/admin/costs/index.html.erb
<h2 class="text-center"><%= t ".cost" %></h2>
<div class="pull-left btn-add-cost">
  <%= link_to "  Tạo mới", new_admin_cost_path,
    class: "fa fa-plus btn btn-default" %>
</div>
<div id="table-costs">
  <table class="table table-hover new-order table-bordered">
    <thead>
      <tr class="info row">
        <th class="col-md-1"><%= t ".month" %></th>
        <th class="col-md-2"><%= t ".amount_electric" %></th>
        <th class="col-md-2"><%= t ".amount_room_electric" %></th>
        <th class="col-md-2"><%= t ".total_payment_electric" %></th>
        <th class="col-md-2"><%= t ".amount_water" %></th>
        <th class="col-md-2"><%= t ".total_payment_water" %></th>
        <th class="col-md-1"></th>
      </tr>
    </thead>
    <tbody>
      <% @costs.each do |cost| %>
        <tr class="row">
          <td class="col-md-1"><%= cost.month ? cost.month.strftime("%m/%Y") : cost.month %></td>
          <td class="col-md-2"><%= cost.amount_electric %></td>
          <td class="col-md-2"><%= cost.room_costs.sum(:amount_electric_consumption) %></td>
          <td class="col-md-2"><%= cost.total_payment_electric ? number_to_currency(cost.total_payment_electric, unit: "VND", delimiter: ".", separator: ",", format: "%n %u") : cost.total_payment_electric %></td>
          <td class="col-md-2"><%= cost.amount_water %></td>
          <td class="col-md-2"><%= cost.total_payment_water ? number_to_currency(cost.total_payment_water, unit: "VND", delimiter: ".", separator: ",", format: "%n %u") : cost.total_payment_water %></td>
          <td class="col-md-1">
            <%= link_to edit_admin_cost_path(cost),
              class: "btn btn-default button-1" do %>
              <i class="fa fa-wrench"> Chỉnh sửa </i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <%= paginate @costs %>
    </tbody>
  </table>
</div>

app/views/admin/costs/new.html.erb
<h2 class="text-center"><%= t ".create_cost" %></h2>
<%= render "form" %>