config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations",
    sessions: "sessions"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  resources :users
  namespace :admin do
    root "admins#index", as: :root
    resources :costs, :rooms, :room_costs
    resources :users do
      get "get_user_cost_info", on: :collection
    end
    resources :statistic
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= t ".the" %> <a href="http://www.goodhouse.org/"><%= t ".home_management" %></a>
  <%= t ".by" %> <a href="tuantv413@gmail.com"><%= t ".author" %></a>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only"><%= t ".toggle_navigation" %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <p>
          <%= t ".home_management" %>
        </p>
      </a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="navc"><%= link_to t(".caculate_cost"), admin_root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to t(".profile"), user_path(current_user) %></li>
        <% end %>
        <li class="navc"><%= link_to t(".help"), "/help" %></li>
        <li class="navc"><%= link_to t(".about"), "/about" %></li>
        <% if user_signed_in? %>
          <li class="dropdown navc">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(".account") %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to t(".settings"), edit_user_registration_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="navc"><%= link_to t(".login"), new_user_session_path %></li>
          <li class="navc"><%= link_to t(".signup"), new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t ".admin" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "admin", "data-turbolinks-track": true  %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            # <span class="icon-bar"></span>
            # <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/admin">
            <span><%= t ".admin" %><%= t(".page") %></span>
          </a>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row content-work">
        <div class="sidebar col-md-2">
          <ul id="nav">
            <li>
              <a href="/admin">
                <i class="fa fa-dashboard"></i><%= t ".dashboard" %>
              </a>
            </li>
            <li>
              <%= link_to admin_costs_path do %>
                <i class="fas fa-dollar-sign"></i>
                <%= t ".list_costs" %>
                <% end %>
            </li>
            <li>
              <%= link_to admin_rooms_path do %>
                <i class="fas fa-warehouse"></i>
                <%= t ".list_rooms" %>
              <% end %>
            </li>
            <li>
              <%= link_to admin_room_costs_path do %>
                <i class="fas fa-hand-holding-usd"></i>
                <%= t ".list_room_costs" %>
              <% end %>
            </li>
            <li>
              <%= link_to admin_users_path do %>
                <i class="fas fa-users"></i>
                <%= t ".list_users" %>
              <% end %>
            </li>
            <li><%= link_to t(".home_page"), root_path %></li>
          </ul>
        </div>
        <div class="content col-md-10 col-md-offset-2">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "good_house" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: :all,
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container main-body">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>